# Generated by Django 4.1.2 on 2022-11-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='funcionario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('senha', models.CharField(max_length=10)),
            ],
        ),
    ]
