# Generated by Django 4.1.2 on 2022-11-10 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='funcionario',
            new_name='Master',
        ),
    ]
