# Generated by Django 4.1.2 on 2022-11-10 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0002_rename_funcionario_master'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Master',
            new_name='UserMaster',
        ),
    ]
