# Generated by Django 4.1.2 on 2022-11-11 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0003_rename_master_usermaster'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserMaster',
            new_name='carla',
        ),
    ]
