# Generated by Django 4.1.2 on 2022-11-11 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0005_usermaster_delete_carla'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserMaster',
        ),
    ]
