# Generated by Django 4.1.2 on 2022-11-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0014_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='cpf',
        ),
        migrations.AlterField(
            model_name='form',
            name='cep',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='form',
            name='numero',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='form',
            name='rg',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='form',
            name='tel',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='form',
            name='tel2',
            field=models.CharField(max_length=12),
        ),
    ]
