# Generated by Django 4.1.2 on 2022-11-12 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0015_remove_form_cpf_alter_form_cep_alter_form_numero_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='form',
        ),
    ]
