# Generated by Django 4.1.2 on 2022-11-12 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0023_form'),
    ]

    operations = [
        migrations.DeleteModel(
            name='form',
        ),
    ]
