# Generated by Django 4.1.2 on 2022-11-16 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0025_form'),
    ]

    operations = [
        migrations.DeleteModel(
            name='form',
        ),
    ]
