# Generated by Django 4.1.2 on 2022-11-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0026_delete_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('dtnc', models.DateField()),
                ('cpf', models.IntegerField()),
                ('rg', models.CharField(max_length=15)),
                ('sexo', models.CharField(choices=[('m', 'Masculino'), ('f', 'Feminino'), ('lgbt', 'Prefiro não opinar')], max_length=4)),
                ('obs', models.CharField(max_length=200)),
            ],
        ),
    ]
