# Generated by Django 4.1.2 on 2022-11-16 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0027_form'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='form',
            new_name='formu',
        ),
    ]
