# Generated by Django 4.1.2 on 2022-11-16 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0033_alter_form_cep_alter_form_cpf_alter_form_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='dt_nasc',
            field=models.DateField(),
        ),
    ]
