# Generated by Django 4.1.2 on 2022-11-17 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0036_alter_form_dt_nasc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='form',
        ),
    ]
